AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Api:
        BinaryMediaTypes:
            - image~1png
    Function:
        Timeout: 3


Resources:
    Bucket:
        Type: AWS::S3::Bucket

    GyazoUploadFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: app/
            Handler: app.gyazo_upload
            Runtime: ruby2.5
            Policies:
                - AWSLambdaExecute # Managed Policy
                -
                    Version: '2012-10-17' # Policy Document
                    Statement:
                        -
                            Effect: Allow
                            Action:
                                - s3:PutObject
                            Resource: !GetAtt Bucket.Arn
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    BUCKET_NAME: !Ref Bucket
            Events:
                GyazoUpload:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /upload
                        Method: post

Outputs:

    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    HelloWorldFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt GyazoUploadFunction.Arn

    HelloWorldFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt GyazoUploadFunctionRole.Arn
