AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Api:
        BinaryMediaTypes:
            - image~1png
    Function:
        Timeout: 3


Resources:
    Bucket:
        Type: AWS::S3::Bucket
        Properties:
            AccessControl: PublicRead
            WebsiteConfiguration:
                IndexDocument: index.html
                ErrorDocument: error.html
        DeletionPolicy: Retain

    BucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: 
                Ref: Bucket
            PolicyDocument: 
                Statement: 
                    - 
                        Action: 
                            - "s3:GetObject"
                        Effect: "Allow"
                        Resource: 
                            Fn::Join: 
                                - ""
                                - 
                                    - "arn:aws:s3:::"
                                    - 
                                        Ref: Bucket
                                    - "/*"
                        Principal: "*"

    GyazoUploadFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: app/
            Handler: app.gyazo_upload
            Runtime: ruby2.5
            Policies:
                - AWSLambdaExecute # Managed Policy
                -
                    Version: '2012-10-17' # Policy Document
                    Statement:
                        -
                            Effect: Allow
                            Action:
                                - s3:PutObject
                            Resource: !GetAtt Bucket.Arn
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    REGION: !Ref "AWS::Region"
                    BUCKET_NAME: !Ref Bucket
            Events:
                GyazoUpload:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /upload
                        Method: post
